### ISSUE TITLE
Error during pip install

### ISSUE THREAD

**Issue by sunilgug** [jbn/ZigZag#10]
copying ./zigzag/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/zigzag
  running egg_info
  writing ZigZag.egg-info/PKG-INFO
  writing dependency_links to ZigZag.egg-info/dependency_links.txt
  writing top-level names to ZigZag.egg-info/top_level.txt
  reading manifest file 'ZigZag.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.pxd' anywhere in distribution
  writing manifest file 'ZigZag.egg-info/SOURCES.txt'
  copying ./zigzag/core.c -> build/lib.macosx-10.7-x86_64-3.7/zigzag
  running build_ext
  building 'zigzag.core' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/zigzag
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sunilguglani/anaconda3/include -arch x86_64 -I/Users/sunilguglani/anaconda3/include -arch x86_64 -DCYTHON_TRACE=0 -DCYTHON_TRACE_NOGIL=0 -DCYTHON_BINDING=0 -DCYTHON_FAST_PYCCALL=1 -I. -I/Users/sunilguglani/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/sunilguglani/anaconda3/include/python3.7m -c ./zigzag/core.c -o build/temp.macosx-10.7-x86_64-3.7/./zigzag/core.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for zigzag
  Running setup.py clean for zigzag
Failed to build zigzag
Installing collected packages: zigzag
  Running setup.py install for zigzag ... error
    ERROR: Complete output from command /Users/sunilguglani/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-install-kgie7kg8/zigzag/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-record-41ayzta3/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/tests
    copying ./tests/test_core.py -> build/lib.macosx-10.7-x86_64-3.7/tests
    copying ./tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/tests
    creating build/lib.macosx-10.7-x86_64-3.7/zigzag
    copying ./zigzag/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/zigzag
    running egg_info
    writing ZigZag.egg-info/PKG-INFO
    writing dependency_links to ZigZag.egg-info/dependency_links.txt
    writing top-level names to ZigZag.egg-info/top_level.txt
    reading manifest file 'ZigZag.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.pxd' anywhere in distribution
    writing manifest file 'ZigZag.egg-info/SOURCES.txt'
    copying ./zigzag/core.c -> build/lib.macosx-10.7-x86_64-3.7/zigzag
    running build_ext
    building 'zigzag.core' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/zigzag
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sunilguglani/anaconda3/include -arch x86_64 -I/Users/sunilguglani/anaconda3/include -arch x86_64 -DCYTHON_TRACE=0 -DCYTHON_TRACE_NOGIL=0 -DCYTHON_BINDING=0 -DCYTHON_FAST_PYCCALL=1 -I. -I/Users/sunilguglani/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/sunilguglani/anaconda3/include/python3.7m -c ./zigzag/core.c -o build/temp.macosx-10.7-x86_64-3.7/./zigzag/core.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/sunilguglani/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-install-kgie7kg8/zigzag/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-record-41ayzta3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-install-kgie7kg8/zigzag/
(base) bash-3.2$ clear

(base) bash-3.2$ pip install zigzag
Collecting zigzag
  Using cached https://files.pythonhosted.org/packages/f5/13/fc7b92091a6ef23b26c1f4a6196276e226775fb199f533c90b917e1c417e/ZigZag-0.2.2.tar.gz
Building wheels for collected packages: zigzag
  Building wheel for zigzag (setup.py) ... error
  ERROR: Complete output from command /Users/sunilguglani/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-install-mu1yppy6/zigzag/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-wheel-92jj8y_4 --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/tests
  copying ./tests/test_core.py -> build/lib.macosx-10.7-x86_64-3.7/tests
  copying ./tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/tests
  creating build/lib.macosx-10.7-x86_64-3.7/zigzag
  copying ./zigzag/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/zigzag
  running egg_info
  writing ZigZag.egg-info/PKG-INFO
  writing dependency_links to ZigZag.egg-info/dependency_links.txt
  writing top-level names to ZigZag.egg-info/top_level.txt
  reading manifest file 'ZigZag.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.pxd' anywhere in distribution
  writing manifest file 'ZigZag.egg-info/SOURCES.txt'
  copying ./zigzag/core.c -> build/lib.macosx-10.7-x86_64-3.7/zigzag
  running build_ext
  building 'zigzag.core' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/zigzag
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sunilguglani/anaconda3/include -arch x86_64 -I/Users/sunilguglani/anaconda3/include -arch x86_64 -DCYTHON_TRACE=0 -DCYTHON_TRACE_NOGIL=0 -DCYTHON_BINDING=0 -DCYTHON_FAST_PYCCALL=1 -I. -I/Users/sunilguglani/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/sunilguglani/anaconda3/include/python3.7m -c ./zigzag/core.c -o build/temp.macosx-10.7-x86_64-3.7/./zigzag/core.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for zigzag
  Running setup.py clean for zigzag
Failed to build zigzag
Installing collected packages: zigzag
  Running setup.py install for zigzag ... error
    ERROR: Complete output from command /Users/sunilguglani/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-install-mu1yppy6/zigzag/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-record-fdk__r9q/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/tests
    copying ./tests/test_core.py -> build/lib.macosx-10.7-x86_64-3.7/tests
    copying ./tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/tests
    creating build/lib.macosx-10.7-x86_64-3.7/zigzag
    copying ./zigzag/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/zigzag
    running egg_info
    writing ZigZag.egg-info/PKG-INFO
    writing dependency_links to ZigZag.egg-info/dependency_links.txt
    writing top-level names to ZigZag.egg-info/top_level.txt
    reading manifest file 'ZigZag.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.pxd' anywhere in distribution
    writing manifest file 'ZigZag.egg-info/SOURCES.txt'
    copying ./zigzag/core.c -> build/lib.macosx-10.7-x86_64-3.7/zigzag
    running build_ext
    building 'zigzag.core' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/zigzag
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sunilguglani/anaconda3/include -arch x86_64 -I/Users/sunilguglani/anaconda3/include -arch x86_64 -DCYTHON_TRACE=0 -DCYTHON_TRACE_NOGIL=0 -DCYTHON_BINDING=0 -DCYTHON_FAST_PYCCALL=1 -I. -I/Users/sunilguglani/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/sunilguglani/anaconda3/include/python3.7m -c ./zigzag/core.c -o build/temp.macosx-10.7-x86_64-3.7/./zigzag/core.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/sunilguglani/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-install-mu1yppy6/zigzag/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-record-fdk__r9q/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2c/1l14hdq55zxgpvj4rgzcmm3m0000gn/T/pip-install-mu1yppy6/zigzag/
(base) bash-3.2$

**Comment by a5601564** [comment]
same question！！！！！

**Comment by jbn** [comment]
Version `0.3.0` should fix this. I'm now using poetry and it seems more robust for creating the build tools. If not, lmk.
