### ISSUE TITLE
Node to node with the same value

### ISSUE THREAD

**Issue by bonetjoshua** [jbn/ZigZag#14]
There's a mistake in the way the zigzag function applies the peaks and valleys, assigning the same value from one node to the other:
![image](https://user-images.githubusercontent.com/51464032/154305289-d041cba2-f8e1-4559-a87e-76255343384b.png)
If you see in the last row, it goes from -1 to -1.

**Comment by mablue** [comment]
Cuz last rows have not an answer in zigzag function cuz of unknown future!zigzag is not for live real algo trading its just usable when you researching on a future known candle

**Comment by bonetjoshua** [comment]
So from -1 to -1 is because it can't find the last peak or valley?

**Comment by mablue** [comment]
You can find the end of earth by walking?!
