### ISSUE TITLE
Problem with install zigzag

### ISSUE THREAD

**Issue by 631202349** [jbn/ZigZag#15]
Environment：
    ubuntu20.04
    python3.8.10
Description：
    there is an error while I installing zigzag use the command "pip3 install zigzag".So i try to use command"pip3 install --no-cache-dir zigzag" found in the closed issue.It's also didn't work.There is the report below:
Collecting zigzag
  Downloading ZigZag-0.2.2.tar.gz (126 kB)
     |████████████████████████████████| 126 kB 347 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-em3l591v/zigzag/setup.py'"'"'; __file__='"'"'/tmp/pip-install-em3l591v/zigzag/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-em3l591v/zigzag/pip-egg-info
         cwd: /tmp/pip-install-em3l591v/zigzag/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-em3l591v/zigzag/setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

**Comment by mablue** [comment]
ModuleNotFoundError: No module named 'Cython'

**Comment by jbn** [comment]
I just updated the package for better installs with `poetry`. Please try,

```python
pip install zigzag==0.3.0
```

and see if it works.
