### ISSUE TITLE
Problems to install

### ISSUE THREAD

**Issue by enoch777** [jbn/ZigZag#3]
Hi.
I have some troubles for install it on anaconda with python 3.6,

This is the error
```
(C:\ProgramData\Anaconda3\envs\Geolab) C:\Users\Enoch>pip install zigzag
Collecting zigzag
  Using cached ZigZag-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "G:\temp\pip-build-fdd9rd73\zigzag\setup.py", line 77, in <module>
        'linetrace': True}),
      File "C:\ProgramData\Anaconda3\envs\Geolab\lib\site-packages\Cython\Build\Dependencies.py", line 818, in cythonize
        aliases=aliases)
      File "C:\ProgramData\Anaconda3\envs\Geolab\lib\site-packages\Cython\Build\Dependencies.py", line 704, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "C:\ProgramData\Anaconda3\envs\Geolab\lib\site-packages\Cython\Build\Dependencies.py", line 108, in nonempty
        raise ValueError(error_msg)
    ValueError: './zigzag/*.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in G:\temp\pip-build-fdd9rd73\zigzag\
```

**Comment by jbn** [comment]
Should be fixed now. Yet another `MANIFEST.in` related mishap. 

Try 

```sh
pip install --no-cache-dir zigzag
```

now. LMK if it works.

**Comment by enoch777** [comment]
Thank you.
It works.

**Comment by jbn** [comment]
Thanks for the report, @enoch777!

**Comment by shinaigo** [comment]
I also get this error below, I need help please:

Collecting zigzag
  Using cached ZigZag-0.2.2.tar.gz (126 kB)
Building wheels for collected packages: zigzag
  Building wheel for zigzag (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\shinaigo\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SHINAIGO\\AppData\\Local\\Temp\\pip-install-n9oc41w8\\zigzag_de97d15cbcf943a482415ae1a8837402\\setup.py'"'"'; __file__='"'"'C:\\Users\\SHINAIGO\\AppData\\Local\\Temp\\pip-install-n9oc41w8\\zigzag_de97d15cbcf943a482415ae1a8837402\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\SHINAIGO\AppData\Local\Temp\pip-wheel-v7d81c1m'
       cwd: C:\Users\SHINAIGO\AppData\Local\Temp\pip-install-n9oc41w8\zigzag_de97d15cbcf943a482415ae1a8837402\
  Complete output (22 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\tests
  copying .\tests\test_core.py -> build\lib.win-amd64-3.8\tests
  copying .\tests\__init__.py -> build\lib.win-amd64-3.8\tests
  creating build\lib.win-amd64-3.8\zigzag
  copying .\zigzag\__init__.py -> build\lib.win-amd64-3.8\zigzag
  running egg_info
  writing ZigZag.egg-info\PKG-INFO
  writing dependency_links to ZigZag.egg-info\dependency_links.txt
  writing top-level names to ZigZag.egg-info\top_level.txt
  adding license file 'LICENSE.txt' (matched pattern 'LICEN[CS]E*')
  reading manifest file 'ZigZag.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.pxd' anywhere in distribution
  writing manifest file 'ZigZag.egg-info\SOURCES.txt'
  running build_ext
  building 'zigzag.core' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for zigzag

**Comment by zillionare** [comment]
failed in tox installation.

using poetry to manage deps, and add cython/ zigzag to pyproject.toml already as:
`
Cython = "^0.29.28"
ZigZag = "^0.2.2"
`
but when running tox, it fails to install zigzag:
`
no module named Cython
`

add cython and numpy to deps of tox.ini will work:
`
deps = 
    cython
    numpy
`
this will cause cython, numpy be installed pre our build artifact, then zigzag can be built.

hope this help

**Comment by MohsenM3** [comment]
### Hi.
I have some troubles for install zigzag on anaconda with python 3.8.5,
I get this error below, I need help please:
Unfortunately, none of the above solutions worked for me.
`Collecting zigzag
  Using cached ZigZag-0.2.2.tar.gz (126 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: zigzag
  Building wheel for zigzag (setup.py) ... error
  error: subprocess-exited-with-error

  ? python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ?─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\tests
      copying .\tests\test_core.py -> build\lib.win-amd64-3.8\tests
      copying .\tests\__init__.py -> build\lib.win-amd64-3.8\tests
      creating build\lib.win-amd64-3.8\zigzag
      copying .\zigzag\__init__.py -> build\lib.win-amd64-3.8\zigzag
      running egg_info
      writing ZigZag.egg-info\PKG-INFO
      writing dependency_links to ZigZag.egg-info\dependency_links.txt
      writing top-level names to ZigZag.egg-info\top_level.txt
      reading manifest file 'ZigZag.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pxd' anywhere in distribution
      writing manifest file 'ZigZag.egg-info\SOURCES.txt'
      running build_ext
      building 'zigzag.core' extension
      creating build\temp.win-amd64-3.8
      creating build\temp.win-amd64-3.8\Release
      creating build\temp.win-amd64-3.8\Release\zigzag
      cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_TRACE=0 -DCYTHON_TRACE
_NOGIL=0 -DCYTHON_BINDING=0 -DCYTHON_FAST_PYCCALL=1 -I. -Ic:\programdata\anacond
a3\lib\site-packages\numpy\core\include -Ic:\programdata\anaconda3\include -Ic:\
programdata\anaconda3\include /Tc./zigzag\core.c /Fobuild\temp.win-amd64-3.8\Rel
ease\./zigzag\core.obj
      error: command 'cl.exe' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
  ERROR: Failed building wheel for zigzag
  Running setup.py clean for zigzag
Failed to build zigzag
Installing collected packages: zigzag
  Running setup.py install for zigzag ... error
  error: subprocess-exited-with-error

  ? Running setup.py install for zigzag did not run successfully.
  │ exit code: 1
  ?─> [25 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\tests
      copying .\tests\test_core.py -> build\lib.win-amd64-3.8\tests
      copying .\tests\__init__.py -> build\lib.win-amd64-3.8\tests
      creating build\lib.win-amd64-3.8\zigzag
      copying .\zigzag\__init__.py -> build\lib.win-amd64-3.8\zigzag
      running egg_info
      writing ZigZag.egg-info\PKG-INFO
      writing dependency_links to ZigZag.egg-info\dependency_links.txt
      writing top-level names to ZigZag.egg-info\top_level.txt
      reading manifest file 'ZigZag.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pxd' anywhere in distribution
      writing manifest file 'ZigZag.egg-info\SOURCES.txt'
      running build_ext
      building 'zigzag.core' extension
      creating build\temp.win-amd64-3.8
      creating build\temp.win-amd64-3.8\Release
      creating build\temp.win-amd64-3.8\Release\zigzag
      cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCYTHON_TRACE=0 -DCYTHON_TRACE
_NOGIL=0 -DCYTHON_BINDING=0 -DCYTHON_FAST_PYCCALL=1 -I. -Ic:\programdata\anacond
a3\lib\site-packages\numpy\core\include -Ic:\programdata\anaconda3\include -Ic:\
programdata\anaconda3\include /Tc./zigzag\core.c /Fobuild\temp.win-amd64-3.8\Rel
ease\./zigzag\core.obj
      error: command 'cl.exe' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit
h pip.
error: legacy-install-failure

? Encountered error while trying to install package.
?─> zigzag

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`
