### ISSUE TITLE
Install procedure for Anaconda is lacking.

### ISSUE THREAD

**Issue by MarcelDelhez** [jbn/ZigZag#5]
I like to experiment the code till I wanted to install in Anaconda.
Not working ... 
Any idea how to install under Anaconda 3 ?

**Comment by LumberJacksJyss** [comment]
Hi. I don't know if you have solved your problem. 
To install it under Anaconda you could try : 
Under mac for example:

Open the terminal
If you're not under the (base) environment, first type 'source activate your_name_environment'
then 'pip install zigzag'
enjoy
If it's under windows, in the conda terminal, type 'activate your_name_environment' if needed (if you're not working in the (base) environment, else, directly type 'pip install zigzag'.

Of course, don't type the comma, and 'your_name_environment is the name of the anaconda environment under which you want to work.
